source "https://rubygems.org"

gem "rails", "~> 4.1.4"
gem "pg"
gem "sass-rails"
gem "uglifier"
gem "coffee-rails"
gem "slim-rails"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder"
gem "bcrypt"
gem "puma"
gem "simple_form"
gem "bootstrap-sass"
gem "valid_email"
gem "figaro"

group :development, :test do
  gem "spring"
  gem "rspec-rails"
  gem "capybara"
  gem "database_cleaner"
  gem "factory_girl_rails"
end
