default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  host: localhost

development:
  <<: *default
  database: yutani_development
  username: yutani
  password:

test:
  <<: *default
  database: yutani_test

production:
  <<: *default
  database: yutani_production
  username: yutani
  password: <%= ENV['YUTANI_DATABASE_PASSWORD'] %>